//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITES
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class giatour
    {
        [System.ComponentModel.DisplayName("ID")]
        public int id { get; set; }
        [Browsable(false)]
        public Nullable<int> idtour { get; set; }
        [System.ComponentModel.DisplayName("Giá tour")]
        public Nullable<decimal> gia { get; set; }
        [System.ComponentModel.DisplayName("Từ ngày")]
        public Nullable<System.DateTime> tungay { get; set; }
        [System.ComponentModel.DisplayName("Đến ngày")]
        public Nullable<System.DateTime> denngay { get; set; }
        [System.ComponentModel.DisplayName("Tên tour")]
        public string tentour
        {
            get
            {
                return tour.tentour;
            }
        }
        [Browsable(false)]
        public virtual tour tour { get; set; }
    }
}
