//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Data.Entity;
    
    public partial class chitietthanhtoan
    {
        tourdulichEntities db = new tourdulichEntities();
        public int id { get; set; }
        public Nullable<int> idphieuthanhtoan { get; set; }
        public Nullable<int> idchitiet { get; set; }
        public string tenchiphi { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<decimal> gia { get; set; }
        public string gias { get { return String.Format("{0:C}", gia); } }
        public decimal tongs { get; set; }
        public string tong { get { return String.Format("{0:C}", tongs); } }
      
       
    
        public virtual phieuthanhtoan phieuthanhtoan { get; set; }
    }
}
