//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class chitietdiemthamquan
    {
        [System.ComponentModel.DisplayName("ID")]
        public int id { get; set; }
        [Browsable(false)]
        public Nullable<int> idtour { get; set; }
        [Browsable(false)]
        public Nullable<int> iddiadiem { get; set; }
        [System.ComponentModel.DisplayName("Tên tour")]
        public string tentour
        {
            get
            {
                return tour.tentour;
            }
        }
        [System.ComponentModel.DisplayName("Địa Điểm")]
        public string tendd
        {
            get
            {
                return diadiem.tendiadiem;
            }
        }
        [Browsable(false)]
        public virtual diadiem diadiem { get; set; }
        [Browsable(false)]
        public virtual tour tour { get; set; }
    }
}
