//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class diadiem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public diadiem()
        {
            this.chitietdiemthamquans = new HashSet<chitietdiemthamquan>();
        }
        [System.ComponentModel.DisplayName("ID")]
        public int id { get; set; }
        [System.ComponentModel.DisplayName("Tên địa điểm")]
        public string tendiadiem { get; set; }
        [Browsable(false)]
        public Nullable<int> idtt { get; set; }
        [System.ComponentModel.DisplayName("Tỉnh thành")]
        public string tentt
        {
            get
            {
                return tinhthanh.tentt;
            }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Browsable(false)]
        public virtual ICollection<chitietdiemthamquan> chitietdiemthamquans { get; set; }
        [Browsable(false)]
        public virtual tinhthanh tinhthanh { get; set; }
    }
}
