//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class khachhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khachhang()
        {
            this.chitietdoanduliches = new HashSet<chitietdoandulich>();
        }
    
        public int id { get; set; }
        public string tenkhachhang { get; set; }
        public string socmnd { get; set; }
        public string diachi { get; set; }
        public Nullable<int> gioitinh { get; set; }
        public string sodienthoai { get; set; }
        public string socmnd_tenkh
        {
            get
            {
                return socmnd + " -- " + tenkhachhang;
            }
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietdoandulich> chitietdoanduliches { get; set; }
        public virtual gioitinh gioitinh1 { get; set; }
    }
}
