//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tour()
        {
            this.chitietdiemthamquans = new HashSet<chitietdiemthamquan>();
            this.doanduliches = new HashSet<doandulich>();
            this.giatours = new HashSet<giatour>();
        }
    
        public int id { get; set; }
        [System.ComponentModel.DisplayName("Tên tour")]
        public string tentour { get; set; }
        [System.ComponentModel.DisplayName("Đặc điểm")]
        public string dacdiem { get; set; }
        [Browsable(false)]
        public Nullable<int> idlh { get; set; }
        [System.ComponentModel.DisplayName("Loại hình")]
        public string tenlh
        {
            get
            {
                return loaihinhdulich.tenloaihinh;
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Browsable(false)]
        public virtual ICollection<chitietdiemthamquan> chitietdiemthamquans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Browsable(false)]
        public virtual ICollection<doandulich> doanduliches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [Browsable(false)]
        public virtual ICollection<giatour> giatours { get; set; }
        [Browsable(false)]
        public virtual loaihinhdulich loaihinhdulich { get; set; }
    }
}
